version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: analytics_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amazon_analytics_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - C:/Users/Anzer/.cache/kagglehub:/data


  dbt:
    build: .
    container_name: analytics_dbt
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./dbt_amazon:/root/.dbt # Mount the dbt profiles directory
    working_dir:  /app/dbt_amazon # make sure to set the working directory to where the dbt project is located
    command: ["sleep", "infinity"]

volumes:
  pgdata:
